_wandb:
    value:
        cli_version: 0.22.2
        e:
            2rec4qs91z86mwhbbyre6fnlbijtp4es:
                codePath: models\logistic_regression.py
                codePathLocal: models\logistic_regression.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "510973177856"
                        used: "362237181952"
                email: rahul.tfx@gmail.com
                executable: C:\Users\rjdis\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: b41e3c932699183650345aacbe6f0db822e0bc1f
                    remote: https://github.com/leonado10000/research.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-e4297789-6045-185a-e6be-c6d570820172
                host: Leo
                memory:
                    total: "16473034752"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\rjdis\OneDrive\Documents\GitHub\research\models\logistic_regression.py
                python: CPython 3.11.2
                root: C:\Users\rjdis\OneDrive\Documents\GitHub\research
                startedAt: "2025-10-22T15:31:59.809247Z"
                writerId: 2rec4qs91z86mwhbbyre6fnlbijtp4es
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
                - 105
            "3":
                - 16
            "4": 3.11.2
            "5": 0.22.2
            "8":
                - 2
                - 3
            "12": 0.22.2
            "13": windows-amd64
epochs:
    value: 10
input_dim:
    value: 784
lr:
    value: 0.01
output_dim:
    value: 10
